### ISSUE TITLE
Stats files completely empty for CHM1_1.1

### ISSUE THREAD

**Issue by vaschn** [deannachurch/assembly_alignment#4]
Not sure what is going with CHM1_1.1, but regardless of the assembly I run it against (as assm1 or assm2), the stats report is always full of 0s. Compare the results for CHM1_1.1 vs. GRCh38:

/am/ftp-pub-remap/Homo_sapiens/1.7/CHM1_1.1-GRCh38.report
/am/ftp-pub-remap/Homo_sapiens/1.7/GRCh38-CHM1_1.0.report

The reports aren't empty for CHM1_1.1, so I think there's a bug in the stats calculations here.

> > head CHM1_1.1_GRCh38_alignment_stats.txt 
> > ## CHM1_1.1 vs GRCh38 assembly alignment report
> > ## 2016-02-02
> > ## Overall stats
> > # Sequence       NoHit   UnGap_NoHit     Collapse(SP)    Expansion(SP Only)      Inversion       Mix
> > 
> > chr1    0       0       0       0       0       0
> > chr10   0       0       0       0       0       0
> > chr11   0       0       0       0       0       0
> > chr12   0       0       0       0       0       0
> > chr13   0       0       0       0       0       0
> > chr14   0       0       0       0       0       0
> > 
> > head GRCh38_CHM1_1.1_alignment_stats.txt 
> > ## GRCh38 vs CHM1_1.1 assembly alignment report
> > ## 2016-02-02
> > ## Overall stats
> > # Sequence       NoHit   UnGap_NoHit     Collapse(SP)    Expansion(SP Only)      Inversion       Mix
> > 
> > 1       22628242        4357742 418963  573968  97068   21697
> > 2       4531867 3007867 368258  1011210 124002  11579
> > 3       3590224 3419924 30850   332937  0       2866
> > 4       2979453 2628491 151853  477392  0       3909
> > 5       4170177 3996977 184226  1862318 89276   367
> > 6       3021341 2401341 140231  866387  299095  198

**Comment by vaschn** [comment]
Not sure if this is b/c the seq ids don't quite match up? The GenBank report uses  "chr$", but the assm-assm alignment report does not (uses bare numbers for CHM1_1.1 chromosomes). So perhaps it's not recognizing the sequences?

**Comment by vaschn** [comment]
Confirmed this is due to the discrepancy in the GenBank report. I got this to work with a modified report where I stripped out the chr. I'll discuss the issue with GenBank/gpipe (need for consistency in local names in the files
[GCA_000306695.2_CHM1_1.1_assembly_report.nochr.txt](https://github.com/deannachurch/assembly_alignment/files/114423/GCA_000306695.2_CHM1_1.1_assembly_report.nochr.txt)
), but leave this issue open in case it's possible to update the code to make it refractory to this situation.

**Comment by deannachurch** [comment]
Thanks. Things are set up right now to not emit figures unless there are chromosomes representations on both assemblies. If there is a desire to have some graphics in this case, please open an issue with a feature request and some idea of what you want to see. I haven't don this because I'm not quite sure what to do in this situation.

**Comment by vaschn** [comment]
Will do, I'm also not quite sure how to best represent that situation graphically (no chromosomes on one or both assemblies), but will give it thought.

Ultimately, this issue is really about how to handle a specific seq-id discrepancy (chr$ vs. bare number) in the two reports for a given assembly. And I guess that's actually a feature too, since it's management of bad data :)

**Comment by deannachurch** [comment]
I'm hesitant to deal with the ID issue frankly- any solution is going to be a hack- and I do feel like NCBI should be able to produce consistent reports.
