### ISSUE TITLE
Implement top 10 feature

### ISSUE THREAD

**Issue by deannachurch** [deannachurch/assembly_alignment#5]
Implement a feature to emit the top 10 (by size) for each alignment discordance type.

**Comment by vaschn** [comment]
In the top 10 report, the ##SP and ##SP_only sections are reporting the same thing. Review of alignments indicates that "SP_only" is wrong and "SP" is right. 

I think the bug is in here:
{code}
        #sp
        sort_sp=sorted(sp, key=lambda x: x[3], reverse=True)
        sort_sp_ten=sort_sp[:10]
        fh.write("\n##SP\n")
        writeTopTenLine(fh, sort_sp_ten)
        #sp_only
        sort_sp_only=sorted(sp, key=lambda x: x[3], reverse=True) <==should sp be sp_only?
        sort_sp_only_ten=sort_sp_only[:10]
        fh.write("\n##SP_only\n")
        writeTopTenLine(fh, sort_sp_only_ten)
{code}

**Comment by deannachurch** [comment]
Good catch- fixed and pushed.
